
UPDATE `data_wotlk_itemset` SET `id` = 1,`name` = 'Der Gladiator' WHERE `data_wotlk_itemset`.`id` = 1;
UPDATE `data_wotlk_itemset` SET `id` = 41,`name` = 'Dal''Rends Waffen' WHERE `data_wotlk_itemset`.`id` = 41;
UPDATE `data_wotlk_itemset` SET `id` = 65,`name` = 'Kuss der Spinne' WHERE `data_wotlk_itemset`.`id` = 65;
UPDATE `data_wotlk_itemset` SET `id` = 81,`name` = 'Der Postmeister' WHERE `data_wotlk_itemset`.`id` = 81;
UPDATE `data_wotlk_itemset` SET `id` = 121,`name` = 'Leichenhaftes Gewand' WHERE `data_wotlk_itemset`.`id` = 121;
UPDATE `data_wotlk_itemset` SET `id` = 122,`name` = 'Roben des Totenbeschwörers' WHERE `data_wotlk_itemset`.`id` = 122;
UPDATE `data_wotlk_itemset` SET `id` = 123,`name` = 'Ornat des Blutpanzers' WHERE `data_wotlk_itemset`.`id` = 123;
UPDATE `data_wotlk_itemset` SET `id` = 124,`name` = 'Wächter der Totengebeine' WHERE `data_wotlk_itemset`.`id` = 124;
UPDATE `data_wotlk_itemset` SET `id` = 141,`name` = 'Vulkanrüstung' WHERE `data_wotlk_itemset`.`id` = 141;
UPDATE `data_wotlk_itemset` SET `id` = 142,`name` = 'Sturmschleier' WHERE `data_wotlk_itemset`.`id` = 142;
UPDATE `data_wotlk_itemset` SET `id` = 143,`name` = 'Teufelsaurierrüstung' WHERE `data_wotlk_itemset`.`id` = 143;
UPDATE `data_wotlk_itemset` SET `id` = 144,`name` = 'Eisenfederrüstung' WHERE `data_wotlk_itemset`.`id` = 144;
UPDATE `data_wotlk_itemset` SET `id` = 161,`name` = 'Defiasleder' WHERE `data_wotlk_itemset`.`id` = 161;
UPDATE `data_wotlk_itemset` SET `id` = 162,`name` = 'Umarmung der Viper' WHERE `data_wotlk_itemset`.`id` = 162;
UPDATE `data_wotlk_itemset` SET `id` = 163,`name` = 'Kettenrüstung des Scharlachroten Kreuzzugs' WHERE `data_wotlk_itemset`.`id` = 163;
UPDATE `data_wotlk_itemset` SET `id` = 181,`name` = 'Ornat des Magisters' WHERE `data_wotlk_itemset`.`id` = 181;
UPDATE `data_wotlk_itemset` SET `id` = 182,`name` = 'Gewänder des Gläubigen' WHERE `data_wotlk_itemset`.`id` = 182;
UPDATE `data_wotlk_itemset` SET `id` = 183,`name` = 'Nebel der Furcht' WHERE `data_wotlk_itemset`.`id` = 183;
UPDATE `data_wotlk_itemset` SET `id` = 184,`name` = 'Rüstung der Schattenkunst' WHERE `data_wotlk_itemset`.`id` = 184;
UPDATE `data_wotlk_itemset` SET `id` = 185,`name` = 'Herz der Wildnis' WHERE `data_wotlk_itemset`.`id` = 185;
UPDATE `data_wotlk_itemset` SET `id` = 186,`name` = 'Rüstung des Bestienjägers' WHERE `data_wotlk_itemset`.`id` = 186;
UPDATE `data_wotlk_itemset` SET `id` = 187,`name` = 'Die Elemente' WHERE `data_wotlk_itemset`.`id` = 187;
UPDATE `data_wotlk_itemset` SET `id` = 188,`name` = 'Esse des Lichts' WHERE `data_wotlk_itemset`.`id` = 188;
UPDATE `data_wotlk_itemset` SET `id` = 189,`name` = 'Schlachtrüstung der Ehre' WHERE `data_wotlk_itemset`.`id` = 189;
UPDATE `data_wotlk_itemset` SET `id` = 201,`name` = 'Ornat des Arkanisten' WHERE `data_wotlk_itemset`.`id` = 201;
UPDATE `data_wotlk_itemset` SET `id` = 202,`name` = 'Gewänder der Prophezeiung' WHERE `data_wotlk_itemset`.`id` = 202;
UPDATE `data_wotlk_itemset` SET `id` = 203,`name` = 'Teufelsherzroben' WHERE `data_wotlk_itemset`.`id` = 203;
UPDATE `data_wotlk_itemset` SET `id` = 204,`name` = 'Der Nachtmeuchler' WHERE `data_wotlk_itemset`.`id` = 204;
UPDATE `data_wotlk_itemset` SET `id` = 205,`name` = 'Gewänder des Cenarius' WHERE `data_wotlk_itemset`.`id` = 205;
UPDATE `data_wotlk_itemset` SET `id` = 206,`name` = 'Rüstung des Riesenjägers' WHERE `data_wotlk_itemset`.`id` = 206;
UPDATE `data_wotlk_itemset` SET `id` = 207,`name` = 'Die Wut der Erde' WHERE `data_wotlk_itemset`.`id` = 207;
UPDATE `data_wotlk_itemset` SET `id` = 208,`name` = 'Rüstung der Gerechtigkeit' WHERE `data_wotlk_itemset`.`id` = 208;
UPDATE `data_wotlk_itemset` SET `id` = 209,`name` = 'Schlachtrüstung der Macht' WHERE `data_wotlk_itemset`.`id` = 209;
UPDATE `data_wotlk_itemset` SET `id` = 210,`name` = 'Ornat des Netherwinds' WHERE `data_wotlk_itemset`.`id` = 210;
UPDATE `data_wotlk_itemset` SET `id` = 211,`name` = 'Gewänder der Erhabenheit' WHERE `data_wotlk_itemset`.`id` = 211;
UPDATE `data_wotlk_itemset` SET `id` = 212,`name` = 'Roben der Nemesis' WHERE `data_wotlk_itemset`.`id` = 212;
UPDATE `data_wotlk_itemset` SET `id` = 213,`name` = 'Blutfangrüstung' WHERE `data_wotlk_itemset`.`id` = 213;
UPDATE `data_wotlk_itemset` SET `id` = 214,`name` = 'Sturmgrimms Gewänder' WHERE `data_wotlk_itemset`.`id` = 214;
UPDATE `data_wotlk_itemset` SET `id` = 215,`name` = 'Rüstung des Drachenjägers' WHERE `data_wotlk_itemset`.`id` = 215;
UPDATE `data_wotlk_itemset` SET `id` = 216,`name` = 'Die zehn Stürme' WHERE `data_wotlk_itemset`.`id` = 216;
UPDATE `data_wotlk_itemset` SET `id` = 217,`name` = 'Rüstung des Richturteils' WHERE `data_wotlk_itemset`.`id` = 217;
UPDATE `data_wotlk_itemset` SET `id` = 218,`name` = 'Schlachtrüstung des Zorns' WHERE `data_wotlk_itemset`.`id` = 218;
UPDATE `data_wotlk_itemset` SET `id` = 221,`name` = 'Thero-shan''s Gewand' WHERE `data_wotlk_itemset`.`id` = 221;
UPDATE `data_wotlk_itemset` SET `id` = 241,`name` = 'Scherbe der Götter' WHERE `data_wotlk_itemset`.`id` = 241;
UPDATE `data_wotlk_itemset` SET `id` = 261,`name` = 'Seele des Eskhandar' WHERE `data_wotlk_itemset`.`id` = 261;
UPDATE `data_wotlk_itemset` SET `id` = 281,`name` = 'Schlachtrüstung des Feldherren' WHERE `data_wotlk_itemset`.`id` = 281;
UPDATE `data_wotlk_itemset` SET `id` = 282,`name` = 'Schlachtrüstung des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 282;
UPDATE `data_wotlk_itemset` SET `id` = 301,`name` = 'Erderschütterer des Feldherren' WHERE `data_wotlk_itemset`.`id` = 301;
UPDATE `data_wotlk_itemset` SET `id` = 321,`name` = 'Stolz des Imperiums' WHERE `data_wotlk_itemset`.`id` = 321;
UPDATE `data_wotlk_itemset` SET `id` = 341,`name` = 'Ornat des Feldherren' WHERE `data_wotlk_itemset`.`id` = 341;
UPDATE `data_wotlk_itemset` SET `id` = 342,`name` = 'Gewandung des Feldherren' WHERE `data_wotlk_itemset`.`id` = 342;
UPDATE `data_wotlk_itemset` SET `id` = 343,`name` = 'Ornat des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 343;
UPDATE `data_wotlk_itemset` SET `id` = 344,`name` = 'Gewandung des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 344;
UPDATE `data_wotlk_itemset` SET `id` = 345,`name` = 'Roben des Feldherren' WHERE `data_wotlk_itemset`.`id` = 345;
UPDATE `data_wotlk_itemset` SET `id` = 346,`name` = 'Roben des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 346;
UPDATE `data_wotlk_itemset` SET `id` = 347,`name` = 'Gewänder des Feldherren' WHERE `data_wotlk_itemset`.`id` = 347;
UPDATE `data_wotlk_itemset` SET `id` = 348,`name` = 'Gewänder des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 348;
UPDATE `data_wotlk_itemset` SET `id` = 361,`name` = 'Lohn des Feldherren' WHERE `data_wotlk_itemset`.`id` = 361;
UPDATE `data_wotlk_itemset` SET `id` = 362,`name` = 'Lohn des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 362;
UPDATE `data_wotlk_itemset` SET `id` = 381,`name` = 'Zierat des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 381;
UPDATE `data_wotlk_itemset` SET `id` = 382,`name` = 'Zierat des Feldherren' WHERE `data_wotlk_itemset`.`id` = 382;
UPDATE `data_wotlk_itemset` SET `id` = 383,`name` = 'Schlachtrüstung des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 383;
UPDATE `data_wotlk_itemset` SET `id` = 384,`name` = 'Schlachtrüstung des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 384;
UPDATE `data_wotlk_itemset` SET `id` = 386,`name` = 'Erderschütterer des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 386;
UPDATE `data_wotlk_itemset` SET `id` = 387,`name` = 'Ornat des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 387;
UPDATE `data_wotlk_itemset` SET `id` = 388,`name` = 'Ornat des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 388;
UPDATE `data_wotlk_itemset` SET `id` = 389,`name` = 'Gewandung des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 389;
UPDATE `data_wotlk_itemset` SET `id` = 390,`name` = 'Gewandung des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 390;
UPDATE `data_wotlk_itemset` SET `id` = 391,`name` = 'Roben des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 391;
UPDATE `data_wotlk_itemset` SET `id` = 392,`name` = 'Roben des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 392;
UPDATE `data_wotlk_itemset` SET `id` = 393,`name` = 'Gewänder des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 393;
UPDATE `data_wotlk_itemset` SET `id` = 394,`name` = 'Gewänder des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 394;
UPDATE `data_wotlk_itemset` SET `id` = 395,`name` = 'Lohn des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 395;
UPDATE `data_wotlk_itemset` SET `id` = 396,`name` = 'Lohn des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 396;
UPDATE `data_wotlk_itemset` SET `id` = 397,`name` = 'Zierat des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 397;
UPDATE `data_wotlk_itemset` SET `id` = 398,`name` = 'Zierat des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 398;
UPDATE `data_wotlk_itemset` SET `id` = 401,`name` = 'Aegis des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 401;
UPDATE `data_wotlk_itemset` SET `id` = 402,`name` = 'Aegis des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 402;
UPDATE `data_wotlk_itemset` SET `id` = 421,`name` = 'Blutrebengewand' WHERE `data_wotlk_itemset`.`id` = 421;
UPDATE `data_wotlk_itemset` SET `id` = 441,`name` = 'Urzeitliche Fledermaushaut' WHERE `data_wotlk_itemset`.`id` = 441;
UPDATE `data_wotlk_itemset` SET `id` = 442,`name` = 'Harnisch des Bluttigers' WHERE `data_wotlk_itemset`.`id` = 442;
UPDATE `data_wotlk_itemset` SET `id` = 443,`name` = 'Umarmung der Blutseele' WHERE `data_wotlk_itemset`.`id` = 443;
UPDATE `data_wotlk_itemset` SET `id` = 444,`name` = 'Die dunkle Seele' WHERE `data_wotlk_itemset`.`id` = 444;
UPDATE `data_wotlk_itemset` SET `id` = 461,`name` = 'Die Zwillingsklingen von Hakkari' WHERE `data_wotlk_itemset`.`id` = 461;
UPDATE `data_wotlk_itemset` SET `id` = 462,`name` = 'Zanzils Konzentration' WHERE `data_wotlk_itemset`.`id` = 462;
UPDATE `data_wotlk_itemset` SET `id` = 463,`name` = 'Ursegen' WHERE `data_wotlk_itemset`.`id` = 463;
UPDATE `data_wotlk_itemset` SET `id` = 464,`name` = 'Erlass des Oberherren' WHERE `data_wotlk_itemset`.`id` = 464;
UPDATE `data_wotlk_itemset` SET `id` = 465,`name` = 'Gebet der Uralten' WHERE `data_wotlk_itemset`.`id` = 465;
UPDATE `data_wotlk_itemset` SET `id` = 466,`name` = 'Kraft des Mojo' WHERE `data_wotlk_itemset`.`id` = 466;
UPDATE `data_wotlk_itemset` SET `id` = 467,`name` = 'Unbeugsamkeit des Highlanders' WHERE `data_wotlk_itemset`.`id` = 467;
UPDATE `data_wotlk_itemset` SET `id` = 468,`name` = 'Entschlossenheit des Highlanders' WHERE `data_wotlk_itemset`.`id` = 468;
UPDATE `data_wotlk_itemset` SET `id` = 469,`name` = 'Inbrunst des Highlanders' WHERE `data_wotlk_itemset`.`id` = 469;
UPDATE `data_wotlk_itemset` SET `id` = 470,`name` = 'Seelenkraft des Highlanders' WHERE `data_wotlk_itemset`.`id` = 470;
UPDATE `data_wotlk_itemset` SET `id` = 471,`name` = 'Schicksalsmacht des Highlanders' WHERE `data_wotlk_itemset`.`id` = 471;
UPDATE `data_wotlk_itemset` SET `id` = 472,`name` = 'Feuriger Wille des Highlanders' WHERE `data_wotlk_itemset`.`id` = 472;
UPDATE `data_wotlk_itemset` SET `id` = 473,`name` = 'Brennender Eifer des Highlanders' WHERE `data_wotlk_itemset`.`id` = 473;
UPDATE `data_wotlk_itemset` SET `id` = 474,`name` = 'Schlachtrüstung des Vollstreckers' WHERE `data_wotlk_itemset`.`id` = 474;
UPDATE `data_wotlk_itemset` SET `id` = 475,`name` = 'Rüstung des Freidenkers' WHERE `data_wotlk_itemset`.`id` = 475;
UPDATE `data_wotlk_itemset` SET `id` = 476,`name` = 'Ornat des Weissagers' WHERE `data_wotlk_itemset`.`id` = 476;
UPDATE `data_wotlk_itemset` SET `id` = 477,`name` = 'Rüstung des Raubtiers' WHERE `data_wotlk_itemset`.`id` = 477;
UPDATE `data_wotlk_itemset` SET `id` = 478,`name` = 'Rüstzeug des Wildfangs' WHERE `data_wotlk_itemset`.`id` = 478;
UPDATE `data_wotlk_itemset` SET `id` = 479,`name` = 'Gewand des Haruspex' WHERE `data_wotlk_itemset`.`id` = 479;
UPDATE `data_wotlk_itemset` SET `id` = 480,`name` = 'Gewandung des Glaubenshüters' WHERE `data_wotlk_itemset`.`id` = 480;
UPDATE `data_wotlk_itemset` SET `id` = 481,`name` = 'Roben des Besessenen' WHERE `data_wotlk_itemset`.`id` = 481;
UPDATE `data_wotlk_itemset` SET `id` = 482,`name` = 'Roben des Illusionisten' WHERE `data_wotlk_itemset`.`id` = 482;
UPDATE `data_wotlk_itemset` SET `id` = 483,`name` = 'Inbrunst der Entweihten' WHERE `data_wotlk_itemset`.`id` = 483;
UPDATE `data_wotlk_itemset` SET `id` = 484,`name` = 'Seelenkraft der Entweihten' WHERE `data_wotlk_itemset`.`id` = 484;
UPDATE `data_wotlk_itemset` SET `id` = 485,`name` = 'Brennender Eifer der Entweihten' WHERE `data_wotlk_itemset`.`id` = 485;
UPDATE `data_wotlk_itemset` SET `id` = 486,`name` = 'Schicksalsmacht der Entweihten' WHERE `data_wotlk_itemset`.`id` = 486;
UPDATE `data_wotlk_itemset` SET `id` = 487,`name` = 'Unbeugsamkeit der Entweihten' WHERE `data_wotlk_itemset`.`id` = 487;
UPDATE `data_wotlk_itemset` SET `id` = 488,`name` = 'Feuriger Wille der Entweihten' WHERE `data_wotlk_itemset`.`id` = 488;
UPDATE `data_wotlk_itemset` SET `id` = 489,`name` = 'Schwarzer Drachenschuppenpanzer' WHERE `data_wotlk_itemset`.`id` = 489;
UPDATE `data_wotlk_itemset` SET `id` = 490,`name` = 'Grüner Drachenschuppenpanzer' WHERE `data_wotlk_itemset`.`id` = 490;
UPDATE `data_wotlk_itemset` SET `id` = 491,`name` = 'Blauer Drachenschuppenpanzer' WHERE `data_wotlk_itemset`.`id` = 491;
UPDATE `data_wotlk_itemset` SET `id` = 492,`name` = 'Schattenhammerzierat' WHERE `data_wotlk_itemset`.`id` = 492;
UPDATE `data_wotlk_itemset` SET `id` = 493,`name` = 'Gewandung der Genesis' WHERE `data_wotlk_itemset`.`id` = 493;
UPDATE `data_wotlk_itemset` SET `id` = 494,`name` = 'Symbole des endlosen Lebens' WHERE `data_wotlk_itemset`.`id` = 494;
UPDATE `data_wotlk_itemset` SET `id` = 495,`name` = 'Schlachtrüstung der unnachgiebigen Stärke' WHERE `data_wotlk_itemset`.`id` = 495;
UPDATE `data_wotlk_itemset` SET `id` = 496,`name` = 'Schlachtrüstung des Eroberers' WHERE `data_wotlk_itemset`.`id` = 496;
UPDATE `data_wotlk_itemset` SET `id` = 497,`name` = 'Umarmung des Todesboten' WHERE `data_wotlk_itemset`.`id` = 497;
UPDATE `data_wotlk_itemset` SET `id` = 498,`name` = 'Embleme der Schattenschleier' WHERE `data_wotlk_itemset`.`id` = 498;
UPDATE `data_wotlk_itemset` SET `id` = 499,`name` = 'Roben des Verdammnisrufers' WHERE `data_wotlk_itemset`.`id` = 499;
UPDATE `data_wotlk_itemset` SET `id` = 500,`name` = 'Ritualroben der ungesagten Namen' WHERE `data_wotlk_itemset`.`id` = 500;
UPDATE `data_wotlk_itemset` SET `id` = 501,`name` = 'Gewand des Sturmrufers' WHERE `data_wotlk_itemset`.`id` = 501;
UPDATE `data_wotlk_itemset` SET `id` = 502,`name` = 'Gabe der aufziehenden Stürme' WHERE `data_wotlk_itemset`.`id` = 502;
UPDATE `data_wotlk_itemset` SET `id` = 503,`name` = 'Gewänder des Mysteriums' WHERE `data_wotlk_itemset`.`id` = 503;
UPDATE `data_wotlk_itemset` SET `id` = 504,`name` = 'Zierat der behüteten Geheimnisse' WHERE `data_wotlk_itemset`.`id` = 504;
UPDATE `data_wotlk_itemset` SET `id` = 505,`name` = 'Schlachtrüstung des Rächers' WHERE `data_wotlk_itemset`.`id` = 505;
UPDATE `data_wotlk_itemset` SET `id` = 506,`name` = 'Schlachtrüstung der ewigen Gerechtigkeit' WHERE `data_wotlk_itemset`.`id` = 506;
UPDATE `data_wotlk_itemset` SET `id` = 507,`name` = 'Gewänder des Orakels' WHERE `data_wotlk_itemset`.`id` = 507;
UPDATE `data_wotlk_itemset` SET `id` = 508,`name` = 'Pracht der unendlichen Weisheit' WHERE `data_wotlk_itemset`.`id` = 508;
UPDATE `data_wotlk_itemset` SET `id` = 509,`name` = 'Gewand des Hetzers' WHERE `data_wotlk_itemset`.`id` = 509;
UPDATE `data_wotlk_itemset` SET `id` = 510,`name` = 'Zierat des unsichtbaren Pfads' WHERE `data_wotlk_itemset`.`id` = 510;
UPDATE `data_wotlk_itemset` SET `id` = 511,`name` = 'Schlachtrüstung des Heldentums' WHERE `data_wotlk_itemset`.`id` = 511;
UPDATE `data_wotlk_itemset` SET `id` = 512,`name` = 'Rüstung der Finsternis' WHERE `data_wotlk_itemset`.`id` = 512;
UPDATE `data_wotlk_itemset` SET `id` = 513,`name` = 'Ungezähmtes Herz' WHERE `data_wotlk_itemset`.`id` = 513;
UPDATE `data_wotlk_itemset` SET `id` = 514,`name` = 'Gewänder des Tugendhaften' WHERE `data_wotlk_itemset`.`id` = 514;
UPDATE `data_wotlk_itemset` SET `id` = 515,`name` = 'Rüstung der Tierherrschaft' WHERE `data_wotlk_itemset`.`id` = 515;
UPDATE `data_wotlk_itemset` SET `id` = 516,`name` = 'Rüstung der Seelenschmiede' WHERE `data_wotlk_itemset`.`id` = 516;
UPDATE `data_wotlk_itemset` SET `id` = 517,`name` = 'Ornat der Zauberkünste' WHERE `data_wotlk_itemset`.`id` = 517;
UPDATE `data_wotlk_itemset` SET `id` = 518,`name` = 'Roben des Todesnebels' WHERE `data_wotlk_itemset`.`id` = 518;
UPDATE `data_wotlk_itemset` SET `id` = 519,`name` = 'Die fünf Donner' WHERE `data_wotlk_itemset`.`id` = 519;
UPDATE `data_wotlk_itemset` SET `id` = 520,`name` = 'Eisengewebte Kampfrüstung' WHERE `data_wotlk_itemset`.`id` = 520;
UPDATE `data_wotlk_itemset` SET `id` = 521,`name` = 'Gewandung des Traumwandlers' WHERE `data_wotlk_itemset`.`id` = 521;
UPDATE `data_wotlk_itemset` SET `id` = 522,`name` = 'Gewänder des Feldherren' WHERE `data_wotlk_itemset`.`id` = 522;
UPDATE `data_wotlk_itemset` SET `id` = 523,`name` = 'Schlachtrüstung des Schreckenspanzers' WHERE `data_wotlk_itemset`.`id` = 523;
UPDATE `data_wotlk_itemset` SET `id` = 524,`name` = 'Rüstung der Knochensense' WHERE `data_wotlk_itemset`.`id` = 524;
UPDATE `data_wotlk_itemset` SET `id` = 525,`name` = 'Gewänder des Glaubens' WHERE `data_wotlk_itemset`.`id` = 525;
UPDATE `data_wotlk_itemset` SET `id` = 526,`name` = 'Frostfeuerornat' WHERE `data_wotlk_itemset`.`id` = 526;
UPDATE `data_wotlk_itemset` SET `id` = 527,`name` = 'Der Erdspalter' WHERE `data_wotlk_itemset`.`id` = 527;
UPDATE `data_wotlk_itemset` SET `id` = 528,`name` = 'Rüstung der Erlösung' WHERE `data_wotlk_itemset`.`id` = 528;
UPDATE `data_wotlk_itemset` SET `id` = 529,`name` = 'Roben des verseuchten Herzens' WHERE `data_wotlk_itemset`.`id` = 529;
UPDATE `data_wotlk_itemset` SET `id` = 530,`name` = 'Rüstung des Gruftpirschers' WHERE `data_wotlk_itemset`.`id` = 530;
UPDATE `data_wotlk_itemset` SET `id` = 533,`name` = 'Kampfrüstung des Untotenschlachtens' WHERE `data_wotlk_itemset`.`id` = 533;
UPDATE `data_wotlk_itemset` SET `id` = 534,`name` = 'Rüstung des Untotenschlächters' WHERE `data_wotlk_itemset`.`id` = 534;
UPDATE `data_wotlk_itemset` SET `id` = 535,`name` = 'Gewand des Untotenschlächters' WHERE `data_wotlk_itemset`.`id` = 535;
UPDATE `data_wotlk_itemset` SET `id` = 536,`name` = 'Ornat der Untotenbekämpfung' WHERE `data_wotlk_itemset`.`id` = 536;
UPDATE `data_wotlk_itemset` SET `id` = 537,`name` = 'Sturmrüstung des Feldherren' WHERE `data_wotlk_itemset`.`id` = 537;
UPDATE `data_wotlk_itemset` SET `id` = 538,`name` = 'Sturmornat des Feldherren' WHERE `data_wotlk_itemset`.`id` = 538;
UPDATE `data_wotlk_itemset` SET `id` = 539,`name` = 'Haingewand des Feldherren' WHERE `data_wotlk_itemset`.`id` = 539;
UPDATE `data_wotlk_itemset` SET `id` = 540,`name` = 'Würdengewand des Feldherren' WHERE `data_wotlk_itemset`.`id` = 540;
UPDATE `data_wotlk_itemset` SET `id` = 541,`name` = 'Schreckensrüstung des Feldherren' WHERE `data_wotlk_itemset`.`id` = 541;
UPDATE `data_wotlk_itemset` SET `id` = 542,`name` = 'Arkanum des Feldherren' WHERE `data_wotlk_itemset`.`id` = 542;
UPDATE `data_wotlk_itemset` SET `id` = 543,`name` = 'Jagdrüstung des Feldherren' WHERE `data_wotlk_itemset`.`id` = 543;
UPDATE `data_wotlk_itemset` SET `id` = 544,`name` = 'Zeremonienrüstung des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 544;
UPDATE `data_wotlk_itemset` SET `id` = 545,`name` = 'Sturmrüstung des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 545;
UPDATE `data_wotlk_itemset` SET `id` = 546,`name` = 'Arkanum des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 546;
UPDATE `data_wotlk_itemset` SET `id` = 547,`name` = 'Schreckensrüstung des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 547;
UPDATE `data_wotlk_itemset` SET `id` = 548,`name` = 'Gewänder des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 548;
UPDATE `data_wotlk_itemset` SET `id` = 549,`name` = 'Würdengewand des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 549;
UPDATE `data_wotlk_itemset` SET `id` = 550,`name` = 'Jagdrüstung des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 550;
UPDATE `data_wotlk_itemset` SET `id` = 551,`name` = 'Haingewand des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 551;
UPDATE `data_wotlk_itemset` SET `id` = 552,`name` = 'Zorn des Zauberfeuers' WHERE `data_wotlk_itemset`.`id` = 552;
UPDATE `data_wotlk_itemset` SET `id` = 553,`name` = 'Umarmung der Schatten' WHERE `data_wotlk_itemset`.`id` = 553;
UPDATE `data_wotlk_itemset` SET `id` = 554,`name` = 'Urmondroben' WHERE `data_wotlk_itemset`.`id` = 554;
UPDATE `data_wotlk_itemset` SET `id` = 555,`name` = 'Netherstoffgewänder' WHERE `data_wotlk_itemset`.`id` = 555;
UPDATE `data_wotlk_itemset` SET `id` = 556,`name` = 'Magiererfüllte Netherstoffroben' WHERE `data_wotlk_itemset`.`id` = 556;
UPDATE `data_wotlk_itemset` SET `id` = 557,`name` = 'Seelenstoffumarmung' WHERE `data_wotlk_itemset`.`id` = 557;
UPDATE `data_wotlk_itemset` SET `id` = 558,`name` = 'Arkanostoffgewänder' WHERE `data_wotlk_itemset`.`id` = 558;
UPDATE `data_wotlk_itemset` SET `id` = 559,`name` = 'Insignien des Zauberschlags' WHERE `data_wotlk_itemset`.`id` = 559;
UPDATE `data_wotlk_itemset` SET `id` = 560,`name` = 'Teufelseisenplattenrüstung' WHERE `data_wotlk_itemset`.`id` = 560;
UPDATE `data_wotlk_itemset` SET `id` = 561,`name` = 'Teufelseisenkettenrüstung' WHERE `data_wotlk_itemset`.`id` = 561;
UPDATE `data_wotlk_itemset` SET `id` = 562,`name` = 'Adamantitschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 562;
UPDATE `data_wotlk_itemset` SET `id` = 563,`name` = 'Verzauberte Adamantitrüstung' WHERE `data_wotlk_itemset`.`id` = 563;
UPDATE `data_wotlk_itemset` SET `id` = 564,`name` = 'Flammenwächter' WHERE `data_wotlk_itemset`.`id` = 564;
UPDATE `data_wotlk_itemset` SET `id` = 565,`name` = 'Khoriumschutz' WHERE `data_wotlk_itemset`.`id` = 565;
UPDATE `data_wotlk_itemset` SET `id` = 566,`name` = 'Brennender Zorn' WHERE `data_wotlk_itemset`.`id` = 566;
UPDATE `data_wotlk_itemset` SET `id` = 567,`name` = 'Schlachtrüstung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 567;
UPDATE `data_wotlk_itemset` SET `id` = 568,`name` = 'Schreckensrüstung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 568;
UPDATE `data_wotlk_itemset` SET `id` = 569,`name` = 'Teufelsstählerner Wille' WHERE `data_wotlk_itemset`.`id` = 569;
UPDATE `data_wotlk_itemset` SET `id` = 570,`name` = 'Der Unerschütterliche' WHERE `data_wotlk_itemset`.`id` = 570;
UPDATE `data_wotlk_itemset` SET `id` = 571,`name` = 'Weisheit des weißen Heilers' WHERE `data_wotlk_itemset`.`id` = 571;
UPDATE `data_wotlk_itemset` SET `id` = 572,`name` = 'Gewand des Schlachtenzaubers' WHERE `data_wotlk_itemset`.`id` = 572;
UPDATE `data_wotlk_itemset` SET `id` = 573,`name` = 'Teufelshaut' WHERE `data_wotlk_itemset`.`id` = 573;
UPDATE `data_wotlk_itemset` SET `id` = 574,`name` = 'Macht der Grollhufe' WHERE `data_wotlk_itemset`.`id` = 574;
UPDATE `data_wotlk_itemset` SET `id` = 575,`name` = 'Rüstung des Teufelspirschers' WHERE `data_wotlk_itemset`.`id` = 575;
UPDATE `data_wotlk_itemset` SET `id` = 576,`name` = 'Netherzorn' WHERE `data_wotlk_itemset`.`id` = 576;
UPDATE `data_wotlk_itemset` SET `id` = 577,`name` = 'Gewänder des Gladiators' WHERE `data_wotlk_itemset`.`id` = 577;
UPDATE `data_wotlk_itemset` SET `id` = 578,`name` = 'Erderschütterer des Gladiators' WHERE `data_wotlk_itemset`.`id` = 578;
UPDATE `data_wotlk_itemset` SET `id` = 579,`name` = 'Ornat des Gladiators' WHERE `data_wotlk_itemset`.`id` = 579;
UPDATE `data_wotlk_itemset` SET `id` = 580,`name` = 'Donnerfaust des Gladiators' WHERE `data_wotlk_itemset`.`id` = 580;
UPDATE `data_wotlk_itemset` SET `id` = 581,`name` = 'Gewandung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 581;
UPDATE `data_wotlk_itemset` SET `id` = 582,`name` = 'Aegis des Gladiators' WHERE `data_wotlk_itemset`.`id` = 582;
UPDATE `data_wotlk_itemset` SET `id` = 583,`name` = 'Rechtschaffenheit des Gladiators' WHERE `data_wotlk_itemset`.`id` = 583;
UPDATE `data_wotlk_itemset` SET `id` = 584,`name` = 'Schutzgewandung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 584;
UPDATE `data_wotlk_itemset` SET `id` = 585,`name` = 'Wildfell des Gladiators' WHERE `data_wotlk_itemset`.`id` = 585;
UPDATE `data_wotlk_itemset` SET `id` = 586,`name` = 'Jagdtracht des Gladiators' WHERE `data_wotlk_itemset`.`id` = 586;
UPDATE `data_wotlk_itemset` SET `id` = 587,`name` = 'Aegis des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 587;
UPDATE `data_wotlk_itemset` SET `id` = 588,`name` = 'Schlachtrüstung des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 588;
UPDATE `data_wotlk_itemset` SET `id` = 589,`name` = 'Aegis des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 589;
UPDATE `data_wotlk_itemset` SET `id` = 590,`name` = 'Schlachtrüstung des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 590;
UPDATE `data_wotlk_itemset` SET `id` = 591,`name` = 'Schreckensrüstung des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 591;
UPDATE `data_wotlk_itemset` SET `id` = 592,`name` = 'Schreckensrüstung des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 592;
UPDATE `data_wotlk_itemset` SET `id` = 593,`name` = 'Erderschütterer des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 593;
UPDATE `data_wotlk_itemset` SET `id` = 594,`name` = 'Erderschütterer des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 594;
UPDATE `data_wotlk_itemset` SET `id` = 595,`name` = 'Jagdtracht des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 595;
UPDATE `data_wotlk_itemset` SET `id` = 596,`name` = 'Jagdtracht des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 596;
UPDATE `data_wotlk_itemset` SET `id` = 597,`name` = 'Gewandung des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 597;
UPDATE `data_wotlk_itemset` SET `id` = 598,`name` = 'Gewandung des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 598;
UPDATE `data_wotlk_itemset` SET `id` = 599,`name` = 'Ornat des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 599;
UPDATE `data_wotlk_itemset` SET `id` = 600,`name` = 'Ornat des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 600;
UPDATE `data_wotlk_itemset` SET `id` = 601,`name` = 'Schutzgewandung des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 601;
UPDATE `data_wotlk_itemset` SET `id` = 602,`name` = 'Schutzgewandung des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 602;
UPDATE `data_wotlk_itemset` SET `id` = 603,`name` = 'Donnerfaust des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 603;
UPDATE `data_wotlk_itemset` SET `id` = 604,`name` = 'Donnerfaust des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 604;
UPDATE `data_wotlk_itemset` SET `id` = 605,`name` = 'Gewänder des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 605;
UPDATE `data_wotlk_itemset` SET `id` = 606,`name` = 'Gewänder des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 606;
UPDATE `data_wotlk_itemset` SET `id` = 607,`name` = 'Rechtschaffenheit des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 607;
UPDATE `data_wotlk_itemset` SET `id` = 608,`name` = 'Rechtschaffenheit des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 608;
UPDATE `data_wotlk_itemset` SET `id` = 609,`name` = 'Wildfell des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 609;
UPDATE `data_wotlk_itemset` SET `id` = 610,`name` = 'Wildfell des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 610;
UPDATE `data_wotlk_itemset` SET `id` = 611,`name` = 'Teufelsschuppenrüstung' WHERE `data_wotlk_itemset`.`id` = 611;
UPDATE `data_wotlk_itemset` SET `id` = 612,`name` = 'Geschuppte draenische Rüstung' WHERE `data_wotlk_itemset`.`id` = 612;
UPDATE `data_wotlk_itemset` SET `id` = 613,`name` = 'Dicke draenische Rüstung' WHERE `data_wotlk_itemset`.`id` = 613;
UPDATE `data_wotlk_itemset` SET `id` = 614,`name` = 'Wilde draenische Rüstung' WHERE `data_wotlk_itemset`.`id` = 614;
UPDATE `data_wotlk_itemset` SET `id` = 615,`name` = 'Teufelsschleier des Gladiators' WHERE `data_wotlk_itemset`.`id` = 615;
UPDATE `data_wotlk_itemset` SET `id` = 616,`name` = 'Netherschuppenrüstung' WHERE `data_wotlk_itemset`.`id` = 616;
UPDATE `data_wotlk_itemset` SET `id` = 617,`name` = 'Rüstung des Netherstoßes' WHERE `data_wotlk_itemset`.`id` = 617;
UPDATE `data_wotlk_itemset` SET `id` = 618,`name` = 'Rüstung des Windfalken' WHERE `data_wotlk_itemset`.`id` = 618;
UPDATE `data_wotlk_itemset` SET `id` = 619,`name` = 'Urgewalt' WHERE `data_wotlk_itemset`.`id` = 619;
UPDATE `data_wotlk_itemset` SET `id` = 620,`name` = 'Rüstung des Meuchelmords' WHERE `data_wotlk_itemset`.`id` = 620;
UPDATE `data_wotlk_itemset` SET `id` = 621,`name` = 'Netherklinge' WHERE `data_wotlk_itemset`.`id` = 621;
UPDATE `data_wotlk_itemset` SET `id` = 622,`name` = 'Todeshauch' WHERE `data_wotlk_itemset`.`id` = 622;
UPDATE `data_wotlk_itemset` SET `id` = 623,`name` = 'Rüstung des Rechtschaffenen' WHERE `data_wotlk_itemset`.`id` = 623;
UPDATE `data_wotlk_itemset` SET `id` = 624,`name` = 'Gewandung des Rechtsprechers' WHERE `data_wotlk_itemset`.`id` = 624;
UPDATE `data_wotlk_itemset` SET `id` = 625,`name` = 'Rüstung des Rechtsprechers' WHERE `data_wotlk_itemset`.`id` = 625;
UPDATE `data_wotlk_itemset` SET `id` = 626,`name` = 'Schlachtrüstung des Rechtsprechers' WHERE `data_wotlk_itemset`.`id` = 626;
UPDATE `data_wotlk_itemset` SET `id` = 627,`name` = 'Kristallgeschmiedete Gewandung' WHERE `data_wotlk_itemset`.`id` = 627;
UPDATE `data_wotlk_itemset` SET `id` = 628,`name` = 'Kristallgeschmiedete Rüstung' WHERE `data_wotlk_itemset`.`id` = 628;
UPDATE `data_wotlk_itemset` SET `id` = 629,`name` = 'Kristallgeschmiedete Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 629;
UPDATE `data_wotlk_itemset` SET `id` = 630,`name` = 'Gewandung des Gezeitensturms' WHERE `data_wotlk_itemset`.`id` = 630;
UPDATE `data_wotlk_itemset` SET `id` = 631,`name` = 'Gewandung des Orkans' WHERE `data_wotlk_itemset`.`id` = 631;
UPDATE `data_wotlk_itemset` SET `id` = 632,`name` = 'Ornat des Orkans' WHERE `data_wotlk_itemset`.`id` = 632;
UPDATE `data_wotlk_itemset` SET `id` = 633,`name` = 'Harnisch des Orkans' WHERE `data_wotlk_itemset`.`id` = 633;
UPDATE `data_wotlk_itemset` SET `id` = 634,`name` = 'Gewandung der Verheerung' WHERE `data_wotlk_itemset`.`id` = 634;
UPDATE `data_wotlk_itemset` SET `id` = 635,`name` = 'Ornat der Verheerung' WHERE `data_wotlk_itemset`.`id` = 635;
UPDATE `data_wotlk_itemset` SET `id` = 636,`name` = 'Harnisch der Verheerung' WHERE `data_wotlk_itemset`.`id` = 636;
UPDATE `data_wotlk_itemset` SET `id` = 637,`name` = 'Gewandung der Mondlichtung' WHERE `data_wotlk_itemset`.`id` = 637;
UPDATE `data_wotlk_itemset` SET `id` = 638,`name` = 'Malornes Gewandung' WHERE `data_wotlk_itemset`.`id` = 638;
UPDATE `data_wotlk_itemset` SET `id` = 639,`name` = 'Malornes Ornat' WHERE `data_wotlk_itemset`.`id` = 639;
UPDATE `data_wotlk_itemset` SET `id` = 640,`name` = 'Malornes Harnisch' WHERE `data_wotlk_itemset`.`id` = 640;
UPDATE `data_wotlk_itemset` SET `id` = 641,`name` = 'Harnisch von Nordrassil' WHERE `data_wotlk_itemset`.`id` = 641;
UPDATE `data_wotlk_itemset` SET `id` = 642,`name` = 'Gewandung von Nordrassil' WHERE `data_wotlk_itemset`.`id` = 642;
UPDATE `data_wotlk_itemset` SET `id` = 643,`name` = 'Ornat von Nordrassil' WHERE `data_wotlk_itemset`.`id` = 643;
UPDATE `data_wotlk_itemset` SET `id` = 644,`name` = 'Gewandung des Vergessens' WHERE `data_wotlk_itemset`.`id` = 644;
UPDATE `data_wotlk_itemset` SET `id` = 645,`name` = 'Gewandung des Herzens der Leere' WHERE `data_wotlk_itemset`.`id` = 645;
UPDATE `data_wotlk_itemset` SET `id` = 646,`name` = 'Gewandung des Verderbers' WHERE `data_wotlk_itemset`.`id` = 646;
UPDATE `data_wotlk_itemset` SET `id` = 647,`name` = 'Ornat des Beschwörens' WHERE `data_wotlk_itemset`.`id` = 647;
UPDATE `data_wotlk_itemset` SET `id` = 648,`name` = 'Ornat der Aldor' WHERE `data_wotlk_itemset`.`id` = 648;
UPDATE `data_wotlk_itemset` SET `id` = 649,`name` = 'Ornat von Tirisfal' WHERE `data_wotlk_itemset`.`id` = 649;
UPDATE `data_wotlk_itemset` SET `id` = 650,`name` = 'Rüstung des Wildtierfürsten' WHERE `data_wotlk_itemset`.`id` = 650;
UPDATE `data_wotlk_itemset` SET `id` = 651,`name` = 'Rüstung des Dämonenwandlers' WHERE `data_wotlk_itemset`.`id` = 651;
UPDATE `data_wotlk_itemset` SET `id` = 652,`name` = 'Rüstung des Dimensionswandlers' WHERE `data_wotlk_itemset`.`id` = 652;
UPDATE `data_wotlk_itemset` SET `id` = 653,`name` = 'Rüstung des Wagemutigen' WHERE `data_wotlk_itemset`.`id` = 653;
UPDATE `data_wotlk_itemset` SET `id` = 654,`name` = 'Rüstung des Kriegshetzers' WHERE `data_wotlk_itemset`.`id` = 654;
UPDATE `data_wotlk_itemset` SET `id` = 655,`name` = 'Schlachtrüstung des Kriegshetzers' WHERE `data_wotlk_itemset`.`id` = 655;
UPDATE `data_wotlk_itemset` SET `id` = 656,`name` = 'Rüstung des Zerstörers' WHERE `data_wotlk_itemset`.`id` = 656;
UPDATE `data_wotlk_itemset` SET `id` = 657,`name` = 'Schlachtrüstung des Zerstörers' WHERE `data_wotlk_itemset`.`id` = 657;
UPDATE `data_wotlk_itemset` SET `id` = 658,`name` = 'Managetränktes Ornat' WHERE `data_wotlk_itemset`.`id` = 658;
UPDATE `data_wotlk_itemset` SET `id` = 659,`name` = 'Ödniswandlerrüstung' WHERE `data_wotlk_itemset`.`id` = 659;
UPDATE `data_wotlk_itemset` SET `id` = 660,`name` = 'Schlachtrüstung der Verwüstung' WHERE `data_wotlk_itemset`.`id` = 660;
UPDATE `data_wotlk_itemset` SET `id` = 661,`name` = 'Verdammnisplattenrüstung' WHERE `data_wotlk_itemset`.`id` = 661;
UPDATE `data_wotlk_itemset` SET `id` = 662,`name` = 'Geheiligte Roben' WHERE `data_wotlk_itemset`.`id` = 662;
UPDATE `data_wotlk_itemset` SET `id` = 663,`name` = 'Gewandung des Leibhaftigen' WHERE `data_wotlk_itemset`.`id` = 663;
UPDATE `data_wotlk_itemset` SET `id` = 664,`name` = 'Ornat des Leibhaftigen' WHERE `data_wotlk_itemset`.`id` = 664;
UPDATE `data_wotlk_itemset` SET `id` = 665,`name` = 'Gewandung des Avatars' WHERE `data_wotlk_itemset`.`id` = 665;
UPDATE `data_wotlk_itemset` SET `id` = 666,`name` = 'Ornat des Avatars' WHERE `data_wotlk_itemset`.`id` = 666;
UPDATE `data_wotlk_itemset` SET `id` = 667,`name` = 'Die Zwillingssterne' WHERE `data_wotlk_itemset`.`id` = 667;
UPDATE `data_wotlk_itemset` SET `id` = 668,`name` = 'Rüstung des Schlächters' WHERE `data_wotlk_itemset`.`id` = 668;
UPDATE `data_wotlk_itemset` SET `id` = 669,`name` = 'Rüstung des Gronnjägers' WHERE `data_wotlk_itemset`.`id` = 669;
UPDATE `data_wotlk_itemset` SET `id` = 670,`name` = 'Gewandung der Boshaftigkeit' WHERE `data_wotlk_itemset`.`id` = 670;
UPDATE `data_wotlk_itemset` SET `id` = 671,`name` = 'Ornat des Gewittersturms' WHERE `data_wotlk_itemset`.`id` = 671;
UPDATE `data_wotlk_itemset` SET `id` = 672,`name` = 'Schlachtrüstung des Ansturms' WHERE `data_wotlk_itemset`.`id` = 672;
UPDATE `data_wotlk_itemset` SET `id` = 673,`name` = 'Rüstung des Ansturms' WHERE `data_wotlk_itemset`.`id` = 673;
UPDATE `data_wotlk_itemset` SET `id` = 674,`name` = 'Ornat der Absolution' WHERE `data_wotlk_itemset`.`id` = 674;
UPDATE `data_wotlk_itemset` SET `id` = 675,`name` = 'Gewänder der Absolution' WHERE `data_wotlk_itemset`.`id` = 675;
UPDATE `data_wotlk_itemset` SET `id` = 676,`name` = 'Harnisch des Donnerherzens' WHERE `data_wotlk_itemset`.`id` = 676;
UPDATE `data_wotlk_itemset` SET `id` = 677,`name` = 'Ornat des Donnerherzens' WHERE `data_wotlk_itemset`.`id` = 677;
UPDATE `data_wotlk_itemset` SET `id` = 678,`name` = 'Gewandung des Donnerherzens' WHERE `data_wotlk_itemset`.`id` = 678;
UPDATE `data_wotlk_itemset` SET `id` = 679,`name` = 'Rüstung des Lichtbringers' WHERE `data_wotlk_itemset`.`id` = 679;
UPDATE `data_wotlk_itemset` SET `id` = 680,`name` = 'Schlachtrüstung des Lichtbringers' WHERE `data_wotlk_itemset`.`id` = 680;
UPDATE `data_wotlk_itemset` SET `id` = 681,`name` = 'Gewandung des Lichtbringers' WHERE `data_wotlk_itemset`.`id` = 681;
UPDATE `data_wotlk_itemset` SET `id` = 682,`name` = 'Harnisch des Himmelsdonners' WHERE `data_wotlk_itemset`.`id` = 682;
UPDATE `data_wotlk_itemset` SET `id` = 683,`name` = 'Gewandung des Himmelsdonners' WHERE `data_wotlk_itemset`.`id` = 683;
UPDATE `data_wotlk_itemset` SET `id` = 684,`name` = 'Ornat des Himmelsdonners' WHERE `data_wotlk_itemset`.`id` = 684;
UPDATE `data_wotlk_itemset` SET `id` = 685,`name` = 'Zuflucht des Gladiators' WHERE `data_wotlk_itemset`.`id` = 685;
UPDATE `data_wotlk_itemset` SET `id` = 686,`name` = 'Kriegsrausch des Gladiators' WHERE `data_wotlk_itemset`.`id` = 686;
UPDATE `data_wotlk_itemset` SET `id` = 687,`name` = 'Vereidigung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 687;
UPDATE `data_wotlk_itemset` SET `id` = 688,`name` = 'Zuflucht des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 688;
UPDATE `data_wotlk_itemset` SET `id` = 689,`name` = 'Zuflucht des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 689;
UPDATE `data_wotlk_itemset` SET `id` = 690,`name` = 'Erlösung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 690;
UPDATE `data_wotlk_itemset` SET `id` = 691,`name` = 'Vereidigung des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 691;
UPDATE `data_wotlk_itemset` SET `id` = 692,`name` = 'Vereidigung des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 692;
UPDATE `data_wotlk_itemset` SET `id` = 693,`name` = 'Erlösung des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 693;
UPDATE `data_wotlk_itemset` SET `id` = 694,`name` = 'Erlösung des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 694;
UPDATE `data_wotlk_itemset` SET `id` = 695,`name` = 'Kriegsrausch des Großmarschalls' WHERE `data_wotlk_itemset`.`id` = 695;
UPDATE `data_wotlk_itemset` SET `id` = 696,`name` = 'Kriegsrausch des Obersten Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 696;
UPDATE `data_wotlk_itemset` SET `id` = 697,`name` = 'Zeremonierüstung des Feldherren' WHERE `data_wotlk_itemset`.`id` = 697;
UPDATE `data_wotlk_itemset` SET `id` = 698,`name` = 'Aegis des Kriegsfürsten' WHERE `data_wotlk_itemset`.`id` = 698;
UPDATE `data_wotlk_itemset` SET `id` = 699,`name` = 'Die Zwillingsklingen von Azzinoth' WHERE `data_wotlk_itemset`.`id` = 699;
UPDATE `data_wotlk_itemset` SET `id` = 700,`name` = 'Aegis des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 700;
UPDATE `data_wotlk_itemset` SET `id` = 701,`name` = 'Schlachtrüstung des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 701;
UPDATE `data_wotlk_itemset` SET `id` = 702,`name` = 'Schreckensrüstung des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 702;
UPDATE `data_wotlk_itemset` SET `id` = 703,`name` = 'Erderschütterer des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 703;
UPDATE `data_wotlk_itemset` SET `id` = 704,`name` = 'Teufelsschleier des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 704;
UPDATE `data_wotlk_itemset` SET `id` = 705,`name` = 'Vereidigung des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 705;
UPDATE `data_wotlk_itemset` SET `id` = 706,`name` = 'Jagdtracht des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 706;
UPDATE `data_wotlk_itemset` SET `id` = 707,`name` = 'Gewandung des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 707;
UPDATE `data_wotlk_itemset` SET `id` = 708,`name` = 'Erlösung des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 708;
UPDATE `data_wotlk_itemset` SET `id` = 709,`name` = 'Zuflucht des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 709;
UPDATE `data_wotlk_itemset` SET `id` = 710,`name` = 'Ornat des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 710;
UPDATE `data_wotlk_itemset` SET `id` = 711,`name` = 'Schutzgewandung des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 711;
UPDATE `data_wotlk_itemset` SET `id` = 712,`name` = 'Donnerfaust des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 712;
UPDATE `data_wotlk_itemset` SET `id` = 713,`name` = 'Gewänder des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 713;
UPDATE `data_wotlk_itemset` SET `id` = 714,`name` = 'Rechtschaffenheit des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 714;
UPDATE `data_wotlk_itemset` SET `id` = 715,`name` = 'Kriegsrausch des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 715;
UPDATE `data_wotlk_itemset` SET `id` = 716,`name` = 'Wildfell des erbarmungslosen Gladiators' WHERE `data_wotlk_itemset`.`id` = 716;
UPDATE `data_wotlk_itemset` SET `id` = 717,`name` = 'Erderschütterer des Feldmarschalls' WHERE `data_wotlk_itemset`.`id` = 717;
UPDATE `data_wotlk_itemset` SET `id` = 718,`name` = 'Erderschütterer des Feldkommandanten' WHERE `data_wotlk_itemset`.`id` = 718;
UPDATE `data_wotlk_itemset` SET `id` = 719,`name` = 'Fäuste des Rächers' WHERE `data_wotlk_itemset`.`id` = 719;
UPDATE `data_wotlk_itemset` SET `id` = 720,`name` = 'Zuflucht des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 720;
UPDATE `data_wotlk_itemset` SET `id` = 721,`name` = 'Schutzgewandung des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 721;
UPDATE `data_wotlk_itemset` SET `id` = 722,`name` = 'Wildfell des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 722;
UPDATE `data_wotlk_itemset` SET `id` = 723,`name` = 'Jagdtracht des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 723;
UPDATE `data_wotlk_itemset` SET `id` = 724,`name` = 'Ornat des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 724;
UPDATE `data_wotlk_itemset` SET `id` = 725,`name` = 'Erlösung des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 725;
UPDATE `data_wotlk_itemset` SET `id` = 726,`name` = 'Rechtschaffenheit des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 726;
UPDATE `data_wotlk_itemset` SET `id` = 727,`name` = 'Aegis des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 727;
UPDATE `data_wotlk_itemset` SET `id` = 728,`name` = 'Vereidigung des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 728;
UPDATE `data_wotlk_itemset` SET `id` = 729,`name` = 'Gewandung des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 729;
UPDATE `data_wotlk_itemset` SET `id` = 730,`name` = 'Gewänder des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 730;
UPDATE `data_wotlk_itemset` SET `id` = 731,`name` = 'Kriegsrausch des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 731;
UPDATE `data_wotlk_itemset` SET `id` = 732,`name` = 'Erderschütterer des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 732;
UPDATE `data_wotlk_itemset` SET `id` = 733,`name` = 'Donnerfaust des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 733;
UPDATE `data_wotlk_itemset` SET `id` = 734,`name` = 'Schreckensrüstung des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 734;
UPDATE `data_wotlk_itemset` SET `id` = 735,`name` = 'Teufelsschleier des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 735;
UPDATE `data_wotlk_itemset` SET `id` = 736,`name` = 'Schlachtrüstung des rachsüchtigen Gladiators' WHERE `data_wotlk_itemset`.`id` = 736;
UPDATE `data_wotlk_itemset` SET `id` = 737,`name` = 'Latros Schlaghagel' WHERE `data_wotlk_itemset`.`id` = 737;
UPDATE `data_wotlk_itemset` SET `id` = 738,`name` = 'Schlachtrüstung aus Schreckenszwirn' WHERE `data_wotlk_itemset`.`id` = 738;
UPDATE `data_wotlk_itemset` SET `id` = 739,`name` = 'Schlachtrüstung aus Mondstoff' WHERE `data_wotlk_itemset`.`id` = 739;
UPDATE `data_wotlk_itemset` SET `id` = 740,`name` = 'Schlachtrüstung aus Satin' WHERE `data_wotlk_itemset`.`id` = 740;
UPDATE `data_wotlk_itemset` SET `id` = 741,`name` = 'Seidene Schlachtrüstung des Beschwörers' WHERE `data_wotlk_itemset`.`id` = 741;
UPDATE `data_wotlk_itemset` SET `id` = 742,`name` = 'Schlachtrüstung aus Drachenleder' WHERE `data_wotlk_itemset`.`id` = 742;
UPDATE `data_wotlk_itemset` SET `id` = 743,`name` = 'Schlachtrüstung aus Wyrmbalg' WHERE `data_wotlk_itemset`.`id` = 743;
UPDATE `data_wotlk_itemset` SET `id` = 744,`name` = 'Schlachtrüstung aus Kodobalg' WHERE `data_wotlk_itemset`.`id` = 744;
UPDATE `data_wotlk_itemset` SET `id` = 745,`name` = 'Schlachtrüstung des Heuchlers' WHERE `data_wotlk_itemset`.`id` = 745;
UPDATE `data_wotlk_itemset` SET `id` = 746,`name` = 'Schwere Schlachtrüstung des Sehers' WHERE `data_wotlk_itemset`.`id` = 746;
UPDATE `data_wotlk_itemset` SET `id` = 747,`name` = 'Ringpanzerschlachtrüstung des Sehers' WHERE `data_wotlk_itemset`.`id` = 747;
UPDATE `data_wotlk_itemset` SET `id` = 748,`name` = 'Gekettelte Schlachtrüstung des Sehers' WHERE `data_wotlk_itemset`.`id` = 748;
UPDATE `data_wotlk_itemset` SET `id` = 749,`name` = 'Kettenschlachtrüstung des Pirschers' WHERE `data_wotlk_itemset`.`id` = 749;
UPDATE `data_wotlk_itemset` SET `id` = 750,`name` = 'Wilde Plattenschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 750;
UPDATE `data_wotlk_itemset` SET `id` = 751,`name` = 'Zieratschlachtrüstung des Kreuzfahrers' WHERE `data_wotlk_itemset`.`id` = 751;
UPDATE `data_wotlk_itemset` SET `id` = 752,`name` = 'Schuppenschlachtrüstung des Kreuzfahrers' WHERE `data_wotlk_itemset`.`id` = 752;
UPDATE `data_wotlk_itemset` SET `id` = 754,`name` = 'Boreanische Umarmung' WHERE `data_wotlk_itemset`.`id` = 754;
UPDATE `data_wotlk_itemset` SET `id` = 755,`name` = 'Nerubischer Schwarm' WHERE `data_wotlk_itemset`.`id` = 755;
UPDATE `data_wotlk_itemset` SET `id` = 756,`name` = 'Frostschuppenbindung' WHERE `data_wotlk_itemset`.`id` = 756;
UPDATE `data_wotlk_itemset` SET `id` = 757,`name` = 'Winterliche Umarmung' WHERE `data_wotlk_itemset`.`id` = 757;
UPDATE `data_wotlk_itemset` SET `id` = 759,`name` = 'Raines Rache' WHERE `data_wotlk_itemset`.`id` = 759;
UPDATE `data_wotlk_itemset` SET `id` = 760,`name` = 'Schreckensplatte des Gladiators' WHERE `data_wotlk_itemset`.`id` = 760;
UPDATE `data_wotlk_itemset` SET `id` = 761,`name` = 'Wintergewandung' WHERE `data_wotlk_itemset`.`id` = 761;
UPDATE `data_wotlk_itemset` SET `id` = 762,`name` = 'Braufesttracht' WHERE `data_wotlk_itemset`.`id` = 762;
UPDATE `data_wotlk_itemset` SET `id` = 763,`name` = 'Frostgewirkte Macht' WHERE `data_wotlk_itemset`.`id` = 763;
UPDATE `data_wotlk_itemset` SET `id` = 764,`name` = 'Dämmerwirker' WHERE `data_wotlk_itemset`.`id` = 764;
UPDATE `data_wotlk_itemset` SET `id` = 765,`name` = 'Schlachtrüstung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 765;
UPDATE `data_wotlk_itemset` SET `id` = 766,`name` = 'Rechtschaffenheit des Gladiators' WHERE `data_wotlk_itemset`.`id` = 766;
UPDATE `data_wotlk_itemset` SET `id` = 767,`name` = 'Erlösung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 767;
UPDATE `data_wotlk_itemset` SET `id` = 768,`name` = 'Entweihung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 768;
UPDATE `data_wotlk_itemset` SET `id` = 769,`name` = 'Donnerfaust des Gladiators' WHERE `data_wotlk_itemset`.`id` = 769;
UPDATE `data_wotlk_itemset` SET `id` = 770,`name` = 'Erderschütterer des Gladiators' WHERE `data_wotlk_itemset`.`id` = 770;
UPDATE `data_wotlk_itemset` SET `id` = 771,`name` = 'Kriegsrausch des Gladiators' WHERE `data_wotlk_itemset`.`id` = 771;
UPDATE `data_wotlk_itemset` SET `id` = 772,`name` = 'Jagdtracht des Gladiators' WHERE `data_wotlk_itemset`.`id` = 772;
UPDATE `data_wotlk_itemset` SET `id` = 773,`name` = 'Zuflucht des Gladiators' WHERE `data_wotlk_itemset`.`id` = 773;
UPDATE `data_wotlk_itemset` SET `id` = 774,`name` = 'Wildfell des Gladiators' WHERE `data_wotlk_itemset`.`id` = 774;
UPDATE `data_wotlk_itemset` SET `id` = 775,`name` = 'Schutzgewandung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 775;
UPDATE `data_wotlk_itemset` SET `id` = 776,`name` = 'Gewänder des Gladiators' WHERE `data_wotlk_itemset`.`id` = 776;
UPDATE `data_wotlk_itemset` SET `id` = 777,`name` = 'Vereidigung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 777;
UPDATE `data_wotlk_itemset` SET `id` = 778,`name` = 'Gewandung des Gladiators' WHERE `data_wotlk_itemset`.`id` = 778;
UPDATE `data_wotlk_itemset` SET `id` = 779,`name` = 'Ornat des Gladiators' WHERE `data_wotlk_itemset`.`id` = 779;
UPDATE `data_wotlk_itemset` SET `id` = 780,`name` = 'Teufelsschleier des Gladiators' WHERE `data_wotlk_itemset`.`id` = 780;
UPDATE `data_wotlk_itemset` SET `id` = 781,`name` = 'Gesegneter Ornat der Untotenbekämpfung' WHERE `data_wotlk_itemset`.`id` = 781;
UPDATE `data_wotlk_itemset` SET `id` = 782,`name` = 'Gesegnete Rüstung des Untotenschlächters' WHERE `data_wotlk_itemset`.`id` = 782;
UPDATE `data_wotlk_itemset` SET `id` = 783,`name` = 'Gesegnetes Gewand des Untotenschlächters' WHERE `data_wotlk_itemset`.`id` = 783;
UPDATE `data_wotlk_itemset` SET `id` = 784,`name` = 'Gesegnete Kampfrüstung des Untotenschlachtens' WHERE `data_wotlk_itemset`.`id` = 784;
UPDATE `data_wotlk_itemset` SET `id` = 785,`name` = 'Sonnenwendfeiernder' WHERE `data_wotlk_itemset`.`id` = 785;
UPDATE `data_wotlk_itemset` SET `id` = 787,`name` = 'Schreckenspanzerplattenrüstung' WHERE `data_wotlk_itemset`.`id` = 787;
UPDATE `data_wotlk_itemset` SET `id` = 788,`name` = 'Schreckenspanzerschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 788;
UPDATE `data_wotlk_itemset` SET `id` = 789,`name` = 'Schlachtrüstung der Erlösung' WHERE `data_wotlk_itemset`.`id` = 789;
UPDATE `data_wotlk_itemset` SET `id` = 790,`name` = 'Ornat der Erlösung' WHERE `data_wotlk_itemset`.`id` = 790;
UPDATE `data_wotlk_itemset` SET `id` = 791,`name` = 'Plattenrüstung der Erlösung' WHERE `data_wotlk_itemset`.`id` = 791;
UPDATE `data_wotlk_itemset` SET `id` = 792,`name` = 'Schlachtrüstung des Geißelerben' WHERE `data_wotlk_itemset`.`id` = 792;
UPDATE `data_wotlk_itemset` SET `id` = 793,`name` = 'Plattenrüstung des Geißelerben' WHERE `data_wotlk_itemset`.`id` = 793;
UPDATE `data_wotlk_itemset` SET `id` = 794,`name` = 'Schlachtrüstung des Gruftpirschers' WHERE `data_wotlk_itemset`.`id` = 794;
UPDATE `data_wotlk_itemset` SET `id` = 795,`name` = 'Erdspalterschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 795;
UPDATE `data_wotlk_itemset` SET `id` = 796,`name` = 'Erdspaltergewand' WHERE `data_wotlk_itemset`.`id` = 796;
UPDATE `data_wotlk_itemset` SET `id` = 797,`name` = 'Erdspalterornat' WHERE `data_wotlk_itemset`.`id` = 797;
UPDATE `data_wotlk_itemset` SET `id` = 798,`name` = 'Schlachtrüstung des Traumwandlers' WHERE `data_wotlk_itemset`.`id` = 798;
UPDATE `data_wotlk_itemset` SET `id` = 799,`name` = 'Ornat des Traumwandlers' WHERE `data_wotlk_itemset`.`id` = 799;
UPDATE `data_wotlk_itemset` SET `id` = 800,`name` = 'Gewand des Traumwandlers' WHERE `data_wotlk_itemset`.`id` = 800;
UPDATE `data_wotlk_itemset` SET `id` = 801,`name` = 'Schlachtrüstung der Knochensense' WHERE `data_wotlk_itemset`.`id` = 801;
UPDATE `data_wotlk_itemset` SET `id` = 802,`name` = 'Gewand des verseuchten Herzens' WHERE `data_wotlk_itemset`.`id` = 802;
UPDATE `data_wotlk_itemset` SET `id` = 803,`name` = 'Frostfeuergewand' WHERE `data_wotlk_itemset`.`id` = 803;
UPDATE `data_wotlk_itemset` SET `id` = 804,`name` = 'Ornat des Glaubens' WHERE `data_wotlk_itemset`.`id` = 804;
UPDATE `data_wotlk_itemset` SET `id` = 805,`name` = 'Gewand des Glaubens' WHERE `data_wotlk_itemset`.`id` = 805;
UPDATE `data_wotlk_itemset` SET `id` = 812,`name` = 'Frühlingsfrack' WHERE `data_wotlk_itemset`.`id` = 812;
UPDATE `data_wotlk_itemset` SET `id` = 813,`name` = 'Schlachtrüstung des Ausweiders' WHERE `data_wotlk_itemset`.`id` = 813;
UPDATE `data_wotlk_itemset` SET `id` = 814,`name` = 'Verzierte Saronitschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 814;
UPDATE `data_wotlk_itemset` SET `id` = 815,`name` = 'Unwetterschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 815;
UPDATE `data_wotlk_itemset` SET `id` = 816,`name` = 'Wilde Saronitschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 816;
UPDATE `data_wotlk_itemset` SET `id` = 817,`name` = 'Sturmbalgschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 817;
UPDATE `data_wotlk_itemset` SET `id` = 818,`name` = 'Flinkpfeilschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 818;
UPDATE `data_wotlk_itemset` SET `id` = 819,`name` = 'Frostgrimmschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 819;
UPDATE `data_wotlk_itemset` SET `id` = 820,`name` = 'Schlachtrüstung der Aegis' WHERE `data_wotlk_itemset`.`id` = 820;
UPDATE `data_wotlk_itemset` SET `id` = 821,`name` = 'Plattenrüstung der Aegis' WHERE `data_wotlk_itemset`.`id` = 821;
UPDATE `data_wotlk_itemset` SET `id` = 822,`name` = 'Ornat der Aegis' WHERE `data_wotlk_itemset`.`id` = 822;
UPDATE `data_wotlk_itemset` SET `id` = 823,`name` = 'Schlachtrüstung des Weltenbrechers' WHERE `data_wotlk_itemset`.`id` = 823;
UPDATE `data_wotlk_itemset` SET `id` = 824,`name` = 'Gewandung des Weltenbrechers' WHERE `data_wotlk_itemset`.`id` = 824;
UPDATE `data_wotlk_itemset` SET `id` = 825,`name` = 'Ornat des Weltenbrechers' WHERE `data_wotlk_itemset`.`id` = 825;
UPDATE `data_wotlk_itemset` SET `id` = 826,`name` = 'Schlachtrüstung der Schreckensklinge' WHERE `data_wotlk_itemset`.`id` = 826;
UPDATE `data_wotlk_itemset` SET `id` = 827,`name` = 'Schlachtrüstung des Nachtweisen' WHERE `data_wotlk_itemset`.`id` = 827;
UPDATE `data_wotlk_itemset` SET `id` = 828,`name` = 'Gewand des Nachtweisen' WHERE `data_wotlk_itemset`.`id` = 828;
UPDATE `data_wotlk_itemset` SET `id` = 829,`name` = 'Ornat des Nachtweisen' WHERE `data_wotlk_itemset`.`id` = 829;
UPDATE `data_wotlk_itemset` SET `id` = 830,`name` = 'Schlachtrüstung des Blockadenbrechers' WHERE `data_wotlk_itemset`.`id` = 830;
UPDATE `data_wotlk_itemset` SET `id` = 831,`name` = 'Plattenrüstung des Blockadenbrechers' WHERE `data_wotlk_itemset`.`id` = 831;
UPDATE `data_wotlk_itemset` SET `id` = 832,`name` = 'Gewandung der Weihe' WHERE `data_wotlk_itemset`.`id` = 832;
UPDATE `data_wotlk_itemset` SET `id` = 833,`name` = 'Ornat der Weihe' WHERE `data_wotlk_itemset`.`id` = 833;
UPDATE `data_wotlk_itemset` SET `id` = 834,`name` = 'Dunkle Runenschlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 834;
UPDATE `data_wotlk_itemset` SET `id` = 835,`name` = 'Dunkle Runenplattenrüstung' WHERE `data_wotlk_itemset`.`id` = 835;
UPDATE `data_wotlk_itemset` SET `id` = 836,`name` = 'Gewand der Kirin Tor' WHERE `data_wotlk_itemset`.`id` = 836;
UPDATE `data_wotlk_itemset` SET `id` = 837,`name` = 'Gewandung des Todesbringers' WHERE `data_wotlk_itemset`.`id` = 837;
UPDATE `data_wotlk_itemset` SET `id` = 838,`name` = 'Schlachtrüstung des Geißeljägers' WHERE `data_wotlk_itemset`.`id` = 838;
UPDATE `data_wotlk_itemset` SET `id` = 843,`name` = 'Khadgars Ornat' WHERE `data_wotlk_itemset`.`id` = 843;
UPDATE `data_wotlk_itemset` SET `id` = 844,`name` = 'Sonnenwanderers Ornat' WHERE `data_wotlk_itemset`.`id` = 844;
UPDATE `data_wotlk_itemset` SET `id` = 845,`name` = 'Gul''dans Ornat' WHERE `data_wotlk_itemset`.`id` = 845;
UPDATE `data_wotlk_itemset` SET `id` = 846,`name` = 'Kel''Thuzads Ornat' WHERE `data_wotlk_itemset`.`id` = 846;
UPDATE `data_wotlk_itemset` SET `id` = 847,`name` = 'Velens Gewandung' WHERE `data_wotlk_itemset`.`id` = 847;
UPDATE `data_wotlk_itemset` SET `id` = 848,`name` = 'Zabras Gewandung' WHERE `data_wotlk_itemset`.`id` = 848;
UPDATE `data_wotlk_itemset` SET `id` = 849,`name` = 'Velens Ornat' WHERE `data_wotlk_itemset`.`id` = 849;
UPDATE `data_wotlk_itemset` SET `id` = 850,`name` = 'Zabras Ornat' WHERE `data_wotlk_itemset`.`id` = 850;
UPDATE `data_wotlk_itemset` SET `id` = 851,`name` = 'Malfurions Gewand' WHERE `data_wotlk_itemset`.`id` = 851;
UPDATE `data_wotlk_itemset` SET `id` = 852,`name` = 'Runentotems Gewand' WHERE `data_wotlk_itemset`.`id` = 852;
UPDATE `data_wotlk_itemset` SET `id` = 853,`name` = 'Malfurions Ornat' WHERE `data_wotlk_itemset`.`id` = 853;
UPDATE `data_wotlk_itemset` SET `id` = 854,`name` = 'Runentotems Ornat' WHERE `data_wotlk_itemset`.`id` = 854;
UPDATE `data_wotlk_itemset` SET `id` = 855,`name` = 'Malfurions Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 855;
UPDATE `data_wotlk_itemset` SET `id` = 856,`name` = 'Runentotems Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 856;
UPDATE `data_wotlk_itemset` SET `id` = 857,`name` = 'Van Cleefs Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 857;
UPDATE `data_wotlk_itemset` SET `id` = 858,`name` = 'Garonas Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 858;
UPDATE `data_wotlk_itemset` SET `id` = 859,`name` = 'Windläufers Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 859;
UPDATE `data_wotlk_itemset` SET `id` = 860,`name` = 'Windläufers Jagdtracht' WHERE `data_wotlk_itemset`.`id` = 860;
UPDATE `data_wotlk_itemset` SET `id` = 861,`name` = 'Nobundos Gewand' WHERE `data_wotlk_itemset`.`id` = 861;
UPDATE `data_wotlk_itemset` SET `id` = 862,`name` = 'Thralls Gewand' WHERE `data_wotlk_itemset`.`id` = 862;
UPDATE `data_wotlk_itemset` SET `id` = 863,`name` = 'Thralls Ornat' WHERE `data_wotlk_itemset`.`id` = 863;
UPDATE `data_wotlk_itemset` SET `id` = 864,`name` = 'Nobundos Ornat' WHERE `data_wotlk_itemset`.`id` = 864;
UPDATE `data_wotlk_itemset` SET `id` = 865,`name` = 'Nobundos Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 865;
UPDATE `data_wotlk_itemset` SET `id` = 866,`name` = 'Thralls Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 866;
UPDATE `data_wotlk_itemset` SET `id` = 867,`name` = 'Wrynns Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 867;
UPDATE `data_wotlk_itemset` SET `id` = 868,`name` = 'Höllschreis Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 868;
UPDATE `data_wotlk_itemset` SET `id` = 869,`name` = 'Wrynns Plattenrüstung' WHERE `data_wotlk_itemset`.`id` = 869;
UPDATE `data_wotlk_itemset` SET `id` = 870,`name` = 'Höllschreis Plattenrüstung' WHERE `data_wotlk_itemset`.`id` = 870;
UPDATE `data_wotlk_itemset` SET `id` = 871,`name` = 'Thassarians Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 871;
UPDATE `data_wotlk_itemset` SET `id` = 872,`name` = 'Koltiras Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 872;
UPDATE `data_wotlk_itemset` SET `id` = 873,`name` = 'Thassarians Plattenrüstung' WHERE `data_wotlk_itemset`.`id` = 873;
UPDATE `data_wotlk_itemset` SET `id` = 874,`name` = 'Koltiras Plattenrüstung' WHERE `data_wotlk_itemset`.`id` = 874;
UPDATE `data_wotlk_itemset` SET `id` = 875,`name` = 'Turalyons Gewand' WHERE `data_wotlk_itemset`.`id` = 875;
UPDATE `data_wotlk_itemset` SET `id` = 876,`name` = 'Liadrins Gewand' WHERE `data_wotlk_itemset`.`id` = 876;
UPDATE `data_wotlk_itemset` SET `id` = 877,`name` = 'Turalyons Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 877;
UPDATE `data_wotlk_itemset` SET `id` = 878,`name` = 'Liadrins Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 878;
UPDATE `data_wotlk_itemset` SET `id` = 879,`name` = 'Turalyons Plattenrüstung' WHERE `data_wotlk_itemset`.`id` = 879;
UPDATE `data_wotlk_itemset` SET `id` = 880,`name` = 'Liadrins Plattenrüstung' WHERE `data_wotlk_itemset`.`id` = 880;
UPDATE `data_wotlk_itemset` SET `id` = 881,`name` = 'Geläuterte Scherbe der Götter' WHERE `data_wotlk_itemset`.`id` = 881;
UPDATE `data_wotlk_itemset` SET `id` = 882,`name` = 'Glänzende Scherbe der Götter' WHERE `data_wotlk_itemset`.`id` = 882;
UPDATE `data_wotlk_itemset` SET `id` = 883,`name` = 'Ornat des Blutmagiers' WHERE `data_wotlk_itemset`.`id` = 883;
UPDATE `data_wotlk_itemset` SET `id` = 884,`name` = 'Ornat des dunklen Zirkels' WHERE `data_wotlk_itemset`.`id` = 884;
UPDATE `data_wotlk_itemset` SET `id` = 885,`name` = 'Roben des purpurroten Akolyten' WHERE `data_wotlk_itemset`.`id` = 885;
UPDATE `data_wotlk_itemset` SET `id` = 886,`name` = 'Ornat des purpurroten Akolyten' WHERE `data_wotlk_itemset`.`id` = 886;
UPDATE `data_wotlk_itemset` SET `id` = 887,`name` = 'Peitschergewirktes Gewand' WHERE `data_wotlk_itemset`.`id` = 887;
UPDATE `data_wotlk_itemset` SET `id` = 888,`name` = 'Peitschergewirktes Ornat' WHERE `data_wotlk_itemset`.`id` = 888;
UPDATE `data_wotlk_itemset` SET `id` = 889,`name` = 'Peitschergewirkte Schlachtrüstung' WHERE `data_wotlk_itemset`.`id` = 889;
UPDATE `data_wotlk_itemset` SET `id` = 890,`name` = 'Schlachtrüstung der Schattenklinge' WHERE `data_wotlk_itemset`.`id` = 890;
UPDATE `data_wotlk_itemset` SET `id` = 891,`name` = 'Blutjägerschlachtrüstung der Ahn''Kahar' WHERE `data_wotlk_itemset`.`id` = 891;
UPDATE `data_wotlk_itemset` SET `id` = 892,`name` = 'Gewand der Frosthexe' WHERE `data_wotlk_itemset`.`id` = 892;
UPDATE `data_wotlk_itemset` SET `id` = 893,`name` = 'Ornat der Frosthexe' WHERE `data_wotlk_itemset`.`id` = 893;
UPDATE `data_wotlk_itemset` SET `id` = 894,`name` = 'Schlachtrüstung der Frosthexe' WHERE `data_wotlk_itemset`.`id` = 894;
UPDATE `data_wotlk_itemset` SET `id` = 895,`name` = 'Schlachtrüstung des Ymirjarfürsten' WHERE `data_wotlk_itemset`.`id` = 895;
UPDATE `data_wotlk_itemset` SET `id` = 896,`name` = 'Plattenrüstung des Ymirjarfürsten' WHERE `data_wotlk_itemset`.`id` = 896;
UPDATE `data_wotlk_itemset` SET `id` = 897,`name` = 'Schlachtrüstung des Geißelfürsten' WHERE `data_wotlk_itemset`.`id` = 897;
UPDATE `data_wotlk_itemset` SET `id` = 898,`name` = 'Plattenrüstung des Geißelfürsten' WHERE `data_wotlk_itemset`.`id` = 898;
UPDATE `data_wotlk_itemset` SET `id` = 899,`name` = 'Gewand des Lichts' WHERE `data_wotlk_itemset`.`id` = 899;
UPDATE `data_wotlk_itemset` SET `id` = 900,`name` = 'Schlachtrüstung des Lichts' WHERE `data_wotlk_itemset`.`id` = 900;
UPDATE `data_wotlk_itemset` SET `id` = 901,`name` = 'Plattenrüstung des Lichts' WHERE `data_wotlk_itemset`.`id` = 901;